[someapp.things.1]
name = "Example Task (repeating date check)"
cmd = "date"
args = []
interval = 4

[someapp.things.2]
name = "Example Task (repeating test message)"
cmd = "echo"
args = ["this is a test"]
interval = 10

[someapp.things.3]
name = "Example Task (remote command)"
cmd = "ssh"
args = ["raspberrypi.local", "-C", "'uname -a'"]
interval = 20
