name: ci/cd

on:
  workflow_dispatch:
  push:
    branches: [ main, 'release/*' ]
  pull_request:
    branches: [ main, 'release/*' ]
  # Build once a month, just to be sure things are still working
  schedule:
    - cron: "19 3 26 * *"

jobs:

  new-builds:
    name: Erlang ${{ matrix.otp_version }} build
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        otp_version: ['27']

    steps:
    - uses: actions/checkout@v2
    - uses: erlef/setup-beam@v1
      with:
        otp-version: ${{ matrix.otp_version }}
        rebar3-version: '3.24'
    - name: Install Deps
      run: sudo apt-get update && sudo apt-get install -y gnuplot
    - name: Compile
      run: rebar3 compile
    - name: Xref Checks
      run: rebar3 xref
    - name: Dialyzer
      run: rebar3 dialyzer
    - name: Proper Tests
      run: rebar3 as test do compile, proper --regressions
    # - name: Run Tests
    #   run: rebar3 ct -c
    - name: Run Unit Tests
      run: rebar3 as test lfe ltest -tall
    # - name: Test Coverage
    #   run: rebar3 as test do proper -c, cover -v --min_coverage=0

  stable-builds:
    name: Erlang ${{ matrix.otp_version }} build
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        otp_version: ['26', '25', '24']

    steps:
    - uses: actions/checkout@v2
    - uses: erlef/setup-beam@v1
      with:
        otp-version: ${{ matrix.otp_version }}
        rebar3-version: '3.22'
    - name: Install Deps
      run: sudo apt-get update && sudo apt-get install -y gnuplot
    - name: Compile
      run: rebar3 compile
    - name: Xref Checks
      run: rebar3 xref
    - name: Dialyzer
      run: rebar3 dialyzer
    - name: Proper Tests
      run: rebar3 as test do compile, proper --regressions
    # - name: Run Tests
    #   run: rebar3 ct -c
    - name: Run Unit Tests
      run: rebar3 as test lfe ltest -tall
    # - name: Test Coverage
    #   run: rebar3 as test do proper -c, cover -v --min_coverage=0

  older-builds:
    name: Erlang ${{ matrix.otp_version }} build
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        otp_version: ['23', '22', '21']

    steps:
    - uses: actions/checkout@v2
    - uses: erlef/setup-beam@v1
      with:
        otp-version: ${{ matrix.otp_version }}
        rebar3-version: '3.15'
    - name: Install Deps
      run: sudo apt-get update && sudo apt-get install -y gnuplot
    - name: Compile
      run: rebar3 compile
    - name: Xref Checks
      run: rebar3 xref
    - name: Dialyzer
      run: rebar3 dialyzer
    - name: Compile Tests
      run: rebar3 as test compile
    - name: Proper Tests
      run: rebar3 as test proper --regressions
    # - name: Run Tests
    #   run: rebar3 ct -c
    - name: Run Unit Tests
      run: rebar3 as test lfe ltest -tall
    # - name: Test Coverage
    #   run: rebar3 as test do proper -c, cover -v --min_coverage=0
